# Configuration for welcome - https://github.com/behaviorbot/welcome


# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome
# Comment to be posted to on first time issues

newIssueWelcomeComment: >
  Hello there!👋 Welcome to the project!🚀⚡
  
  Thank you and congrats🎉 for opening your very first issue in this project.
  Recess is a social media platform for students to share their experience/knowledge they gained in their free time.
  Please adhere to our [Code of Conduct](https://github.com/avinashkranjan/Recess/blob/master/CODE_OF_CONDUCT.md).
  Please make sure not to start working on the issue, unless you get assigned to it.😄
  
  
# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome
# Comment to be posted to on PRs from first time contributors in your repository

newPRWelcomeComment: >
  Hello there!👋 Welcome to the project!💖
  
  Thank you and congrats🎉 for opening your first pull request. 
  Recess is a social media platform for students to share their experience/knowledge they gained in their free time.
  Please make sure you have followed our contributing guidlines .🙌🙌 We will get back to you as soon as we can 😄.
  
 
# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge
# Comment to be posted to on pull requests merged by a first time user

firstPRMergeComment: >
  Hello there!👋
  Congrats🎉 on getting your first pull request merged! All the best for your amazing open source journey ahead 🚀.
