export default function styles(theme) {
	return {
    modal: {
      margin: "auto",
      width: "975px",
      maxHeight: "600px",
      outline: "none",
    },
    modalContainer: {
      display: "flex",
      flexDirection: "column",
      backgroundColor: theme.palette.background.default,
      color: theme.palette.text.primary,
      border: "1px solid " + theme.palette.background,
      borderRadius: 4,
      width: "975px",
      height: "600px",
      maxHeight: "600px",
      outline: "none",
    },
    modalHeader: {
      width: "100%",
      height: "50px",
      padding: "15px 20px",
      borderRadius: "4px 4px 0px 0px",
      backgroundColor: theme.palette.secondary.dark,
    },
    modalUsername: {
      display: "inline-block",
      height: "50px",
      width: "100%",
      fontSize: "20px",
    },
    closeModal: {
      position: "absolute",
      top: ".5rem",
      right: "1.5rem",
      cursor: "pointer",
      fontSize: "1.5rem",
    },
    modalMain: {
      display: "flex",
      alignItem: "stretch",
      flexDirection: "row",
      height: "100%",
      padding: 10,
    },
    postImageHolder: {
      flex: "65%",
      margin: "auto 4px auto 4px",
      height: "fit-content",
      width: "100%",
    },
    postImageContainer: {
      boxSizing: "border-box",
      maxHeight: "500px",
      maxWidth: "100%",
      margin: "auto",
    },
    postImage: {
      boxSizing: "border-box",
      display: "inline-block",
      maxHeight: "500px",
      maxWidth: "100%",
      backgroundColor: "black",
      margin: "auto",
    },
    commentContainer: {
      flex: "35%",
      height: "530px",
      maxHeight: "530px",
      overflow: "auto",
    },
    postedComments: {
      padding: "10px 10px 10px 20px",
      // backgroundColor: theme.palette.secondary.dark,
      height: "470px",
      maxHeight: "470px",
      overflow: "auto",
      borderRadius: 4,
    },
    postCommentsContainer: {
      flex: "35%",
      width: "100%",
    },
    postCommentBox: {
      padding: "0 10px 10px 10px",
      margin: "10px 0 0 0",
      display: "grid",
      gridTemplateColumns: "auto 1fr auto",
      width: "100%",
      position: "relative",
    },
    postCommentInput: {
      outline: "none",
      border: 0,
      padding: "10px",
      backgroundColor: theme.palette.secondary.dark,
      color: theme.palette.text.primary,
    },
    emojiPicker: {
      width: 60,
      outline: "none",
      border: 0,
      borderRight: "1px solid " + theme.palette.primary.main,
      backgroundColor: theme.palette.secondary.dark,
      color: theme.palette.text.primary,

      borderRadius: "7px 0px 0px 7px",
    },
    postCommentButton: {
      width: 60,
      outline: "none",
      border: 0,
      borderLeft: "1px solid " + theme.palette.primary.main,
      backgroundColor: theme.palette.secondary.dark,
      color: theme.palette.text.primary,
      borderRadius: "0 7px 7px 0",
    },
  };
}
